// config.js

// 1. EGSRTULUEntry: home_hero_banner, discover_foryou, invest_nextbestaction
const EGSRTULUEntryRes = {
  Issue: "AcquisitionSales",
  InteractionID: "-3569455782704439973",
  ProductName: "",
  CustomerCost: 0.0,
  ContentFormat: "Image",
  SellableEndDate: "19700101T000000.000 GMT",
  Label: " EGSRTULUEntry ",
  PaidLookalikeValue: "",
  Benefits:
    "Action is to increase Term deposit product with bank, for customer with currency other than HKD",
  WhyRelevant: "",
  Sellable: false,
  ProductSearchCriteria: "",
  Name: " EGSRTULUEntry ",
  ShortDescription:
    "Action is to increase Term deposit product with bank, for customer with currency other than HKD",
  GroupID: "Deposits",
  PaidAudienceName: "",
  Identifier: "/AcquisitionSales/Deposits/ EGSRTULUEntry",
  BundleType: "",
  Placement: " home_hero_banner ",
  SellableStartDate: "19700101T000000.000 GMT",
  JourneyStep: "",
  Propensity: 0.0,
  AgentCompensation: 0,
  BannerLabel: "",
  ClassIdentifier: "Offer",
  Priority: 4.99999999e8,
  Channel: "Mobile",
  BundleName: "",
  ImageURL: "",
  Title2: "",
  Variant: "",
  InternalCost: 0,
  ProductCategory: "",
  Journey: "",
  Group: "Deposits",
  Category: "",
  Message: "立即爲您的3個月USD定存續期，獲享3.89％年利率！",
  SubjectName: "3440000001689575",
  ButtonName2: "",
  Direction: "Inbound",
  ExpectedRevenue: 0.0,
  ButtonName: "解鎖尊屬續期優惠",
  Pricing: "",
  BannerLabel2: "",
  JourneyStage: "",
  EligibilityDescription: "",
  Message2: "",
  Title: "按此解鎖尊屬優惠!",
  Rank: 2,
  ProductID: "",
  BundleParent: "false",
  Treatment: "NewTimeDepositForeignCurrency_TC",
  ProductsCompatible: "",
  AssociatedProductIDs: "",
  CampaignID: "NBA",
  OfferValue: 0,
  SubCategory: "",
  ClickThroughURL: "scmobile://web/htd-webview?specialPricing=Y",
  ProductDescription: "",
  ClickThroughURL2: "",
  SubjectID: "3440000001689575",
  ProductsIncompatible: "",
  DecisionTime: "20250130T040900.486 GMT",
  ContextName: "Customer",
};

// 2. EGSRTULURegistration
const EGSRTULURegistrationRes = {
  Issue: "AcquisitionSales",
  InteractionID: "-3569455782704439973",
  ProductName: "",
  CustomerCost: 0.0,
  ContentFormat: "Image",
  SellableEndDate: "19700101T000000.000 GMT",
  Label: " EGSRTULURegistration",
  PaidLookalikeValue: "",
  Benefits:
    "Action is to increase Term deposit product with bank, for customer with currency other than HKD",
  WhyRelevant: "",
  Sellable: false,
  ProductSearchCriteria: "",
  Name: " EGSRTULURegistration ",
  ShortDescription:
    "Action is to increase Term deposit product with bank, for customer with currency other than HKD",
  GroupID: "Deposits",
  PaidAudienceName: "",
  Identifier: "/AcquisitionSales/Deposits/ EGSRTULURegistration ",
  BundleType: "",
  Placement: "rewards_registration",
  SellableStartDate: "19700101T000000.000 GMT",
  JourneyStep: "",
  Propensity: 0.0,
  AgentCompensation: 0,
  BannerLabel: "",
  ClassIdentifier: "Offer",
  Priority: 4.99999999e8,
  Channel: "Mobile",
  BundleName: "",
  ImageURL: "",
  Title2: "",
  Variant: "",
  InternalCost: 0,
  ProductCategory: "",
  Journey: "",
  Group: "Deposits",
  Category: "",
  Message: "立即爲您的3個月USD定存續期，獲享3.89％年利率！",
  SubjectName: "3440000001689575",
  ButtonName2: "",
  Direction: "Inbound",
  ExpectedRevenue: 0.0,
  ButtonName: "解鎖尊屬續期優惠",
  Pricing: "",
  BannerLabel2: "",
  JourneyStage: "",
  EligibilityDescription: "",
  Message2: "",
  Title: "按此解鎖尊屬優惠!",
  Rank: 2,
  ProductID: "",
  BundleParent: "false",
  Treatment: "NewTimeDepositForeignCurrency_TC",
  ProductsCompatible: "",
  AssociatedProductIDs: "",
  CampaignID: "NBA",
  OfferValue: 0,
  SubCategory: "",
  ClickThroughURL: "scmobile://web/htd-webview?specialPricing=Y",
  ProductDescription: "",
  ClickThroughURL2: "",
  SubjectID: "3440000001689575",
  ProductsIncompatible: "",
  DecisionTime: "20250130T040900.486 GMT",
  ContextName: "Customer",
};

// 3. EGSRTULUDiversify: offers_hub, offers_hub_ghosttile, diversify_page
const EGSRTULUDiversifyRes = {
  Issue: "AcquisitionSales",
  InteractionID: "-3569455782704439973",
  ProductName: "",
  CustomerCost: 0.0,
  ContentFormat: "Image",
  SellableEndDate: "19700101T000000.000 GMT",
  Label: "EGSRTULUDiversify",
  PaidLookalikeValue: "",
  Benefits:
    "Action is to increase Term deposit product with bank, for customer with currency other than HKD",
  WhyRelevant: "",
  Sellable: false,
  ProductSearchCriteria: "",
  Name: "EGSRTULUDiversify",
  ShortDescription:
    "Action is to increase Term deposit product with bank, for customer with currency other than HKD",
  GroupID: "Deposits",
  PaidAudienceName: "",
  Identifier: "/AcquisitionSales/Deposits/EGSRTULUDiversify",
  BundleType: "",
  Placement: "offers_hub",
  SellableStartDate: "19700101T000000.000 GMT",
  JourneyStep: "",
  Propensity: 0.0,
  AgentCompensation: 0,
  BannerLabel: "",
  ClassIdentifier: "Offer",
  Priority: 4.99999999e8,
  Channel: "Mobile",
  BundleName: "",
  ImageURL: "",
  Title2: "",
  Variant: "",
  Fields: [
    {
      Value: "1000",
      Name: "ConsolidatedAmount",
    },
  ],
  InternalCost: 0,
  ProductCategory: "",
  Journey: "",
  Group: "Deposits",
  Category: "",
  Message: "立即爲您的3個月USD定存續期，獲享3.89％年利率！",
  SubjectName: "3440000001689575",
  ButtonName2: "",
  Direction: "Inbound",
  ExpectedRevenue: 0.0,
  ButtonName: "解鎖尊屬續期優惠",
  Pricing: "",
  BannerLabel2: "",
  JourneyStage: "",
  EligibilityDescription: "",
  Message2: "",
  Title: "按此解鎖尊屬優惠!",
  Rank: 2,
  ProductID: "",
  BundleParent: "false",
  Treatment: "NewTimeDepositForeignCurrency_TC",
  ProductsCompatible: "",
  AssociatedProductIDs: "",
  CampaignID: "NBA",
  OfferValue: 0,
  SubCategory: "",
  ClickThroughURL: "scmobile://web/htd-webview?specialPricing=Y",
  ProductDescription: "",
  ClickThroughURL2: "",
  SubjectID: "3440000001689575",
  ProductsIncompatible: "",
  DecisionTime: "20250130T040900.486 GMT",
  ContextName: "Customer",
};

// 4. EGSRTULUTradeUp: offer_hub, offers_hub_ghosttile, tradeup_page
const EGSRTULUTradeUpRes = {
  Issue: "AcquisitionSales",
  InteractionID: "-3569455782704439973",
  ProductName: "",
  CustomerCost: 0.0,
  ContentFormat: "Image",
  SellableEndDate: "19700101T000000.000 GMT",
  Label: "EGSRTULUTradeUp",
  PaidLookalikeValue: "",
  Benefits:
    "Action is to increase Term deposit product with bank, for customer with currency other than HKD",
  WhyRelevant: "",
  Sellable: false,
  ProductSearchCriteria: "",
  Name: " EGSRTULUTradeUp ",
  ShortDescription:
    "Action is to increase Term deposit product with bank, for customer with currency other than HKD",
  GroupID: "Deposits",
  PaidAudienceName: "",
  Identifier: "/AcquisitionSales/Deposits/ EGSRTULUTradeUp ",
  BundleType: "",
  Placement: "offers_hub",
  SellableStartDate: "19700101T000000.000 GMT",
  JourneyStep: "",
  Propensity: 0.0,
  AgentCompensation: 0,
  BannerLabel: "",
  ClassIdentifier: "Offer",
  Priority: 4.99999999e8,
  Channel: "Mobile",
  BundleName: "",
  ImageURL: "",
  Title2: "",
  Variant: "",
  Fields: [
    {
      Value: "1000",
      Name: "ConsolidatedAmount",
    },
  ],
  InternalCost: 0,
  ProductCategory: "",
  Journey: "",
  Group: "Deposits",
  Category: "",
  Message: "立即爲您的3個月USD定存續期，獲享3.89％年利率！",
  SubjectName: "3440000001689575",
  ButtonName2: "",
  Direction: "Inbound",
  ExpectedRevenue: 0.0,
  ButtonName: "解鎖尊屬續期優惠",
  Pricing: "",
  BannerLabel2: "",
  JourneyStage: "",
  EligibilityDescription: "",
  Message2: "",
  Title: "按此解鎖尊屬優惠!",
  Rank: 2,
  ProductID: "",
  BundleParent: "false",
  Treatment: "NewTimeDepositForeignCurrency_TC",
  ProductsCompatible: "",
  AssociatedProductIDs: "",
  CampaignID: "NBA",
  OfferValue: 0,
  SubCategory: "",
  ClickThroughURL: "scmobile://web/htd-webview?specialPricing=Y",
  ProductDescription: "",
  ClickThroughURL2: "",
  SubjectID: "3440000001689575",
  ProductsIncompatible: "",
  DecisionTime: "20250130T040900.486 GMT",
  ContextName: "Customer",
};

// 5. EGSRTULULevelUp: offers_hub, offers_hub_ghosttile
const EGSRTULULevelUpRes = {
  Issue: "AcquisitionSales",
  InteractionID: "-3569455782704439973",
  ProductName: "",
  CustomerCost: 0.0,
  ContentFormat: "Image",
  SellableEndDate: "19700101T000000.000 GMT",
  Label: "EGSRTULULevelUp",
  PaidLookalikeValue: "",
  Benefits:
    "Action is to increase Term deposit product with bank, for customer with currency other than HKD",
  WhyRelevant: "",
  Sellable: false,
  ProductSearchCriteria: "",
  Name: " EGSRTULULevelUp ",
  ShortDescription:
    "Action is to increase Term deposit product with bank, for customer with currency other than HKD",
  GroupID: "Deposits",
  PaidAudienceName: "",
  Identifier: "/AcquisitionSales/Deposits/ EGSRTULULevelUp ",
  BundleType: "",
  Placement: "offers_hub",
  SellableStartDate: "19700101T000000.000 GMT",
  JourneyStep: "",
  Propensity: 0.0,
  AgentCompensation: 0,
  BannerLabel: "",
  ClassIdentifier: "Offer",
  Priority: 4.99999999e8,
  Channel: "Mobile",
  BundleName: "",
  ImageURL: "",
  Title2: "",
  Variant: "",
  Fields: [
    {
      Value: "1000",
      Name: "ConsolidatedAmount",
    },
  ],
  InternalCost: 0,
  ProductCategory: "",
  Journey: "",
  Group: "Deposits",
  Category: "",
  Message: "立即爲您的3個月USD定存續期，獲享3.89％年利率！",
  SubjectName: "3440000001689575",
  ButtonName2: "",
  Direction: "Inbound",
  ExpectedRevenue: 0.0,
  ButtonName: "解鎖尊屬續期優惠",
  Pricing: "",
  BannerLabel2: "",
  JourneyStage: "",
  EligibilityDescription: "",
  Message2: "",
  Title: "按此解鎖尊屬優惠!",
  Rank: 2,
  ProductID: "",
  BundleParent: "false",
  Treatment: "NewTimeDepositForeignCurrency_TC",
  ProductsCompatible: "",
  AssociatedProductIDs: "",
  CampaignID: "NBA",
  OfferValue: 0,
  SubCategory: "",
  ClickThroughURL: "scmobile://web/htd-webview?specialPricing=Y",
  ProductDescription: "",
  ClickThroughURL2: "",
  SubjectID: "3440000001689575",
  ProductsIncompatible: "",
  DecisionTime: "20250130T040900.486 GMT",
  ContextName: "Customer",
};

// 6. EGSRTULUOEDiversify: diversify_page
const EGSRTULUOEDiversifyRes = {
  Issue: "AcquisitionSales",
  InteractionID: "-3569455782704439973",
  ProductName: "",
  CustomerCost: 0.0,
  ContentFormat: "Image",
  SellableEndDate: "19700101T000000.000 GMT",
  Label: " EGSRTULUOEDiversify ",
  PaidLookalikeValue: "",
  Benefits:
    "Action is to increase Term deposit product with bank, for customer with currency other than HKD",
  WhyRelevant: "",
  Sellable: false,
  ProductSearchCriteria: "",
  Name: " EGSRTULUOEDiversify ",
  ShortDescription:
    "Action is to increase Term deposit product with bank, for customer with currency other than HKD",
  GroupID: "Deposits",
  PaidAudienceName: "",
  Identifier: "/AcquisitionSales/Deposits/ EGSRTULUOEDiversify",
  BundleType: "",
  Placement: "diversify_page",
  SellableStartDate: "19700101T000000.000 GMT",
  JourneyStep: "",
  Propensity: 0.0,
  AgentCompensation: 0,
  BannerLabel: "",
  ClassIdentifier: "Offer",
  Priority: 4.99999999e8,
  Channel: "Mobile",
  BundleName: "",
  ImageURL: "",
  Title2: "",
  Variant: "",
  Fields: [
    {
      Value: "Y",
      Name: "OpenAccount",
    },
    {
      Value: "N",
      Name: "FirstTrade",
    },
    {
      Value: "N",
      Name: "CompletionBonus",
    },
  ],

  InternalCost: 0,
  ProductCategory: "",
  Journey: "",
  Group: "Deposits",
  Category: "",
  Message: "立即爲您的3個月USD定存續期，獲享3.89％年利率！",
  SubjectName: "3440000001689575",
  ButtonName2: "",
  Direction: "Inbound",
  ExpectedRevenue: 0.0,
  ButtonName: "解鎖尊屬續期優惠",
  Pricing: "",
  BannerLabel2: "",
  JourneyStage: "",
  EligibilityDescription: "",
  Message2: "",
  Title: "按此解鎖尊屬優惠!",
  Rank: 2,
  ProductID: "",
  BundleParent: "false",
  Treatment: "NewTimeDepositForeignCurrency_TC",
  ProductsCompatible: "",
  AssociatedProductIDs: "",
  CampaignID: "NBA",
  OfferValue: 0,
  SubCategory: "",
  ClickThroughURL: "scmobile://web/htd-webview?specialPricing=Y",
  ProductDescription: "",
  ClickThroughURL2: "",
  SubjectID: "3440000001689575",
  ProductsIncompatible: "",
  DecisionTime: "20250130T040900.486 GMT",
  ContextName: "Customer",
};

// 7. EGSRTULUFXDiversify: diversify_page
const EGSRTULUFXDiversifyRes = {
  Issue: "AcquisitionSales",
  InteractionID: "-3569455782704439973",
  ProductName: "",
  CustomerCost: 0.0,
  ContentFormat: "Image",
  SellableEndDate: "19700101T000000.000 GMT",
  Label: " EGSRTULUFXDiversify ",
  PaidLookalikeValue: "",
  Benefits:
    "Action is to increase Term deposit product with bank, for customer with currency other than HKD",
  WhyRelevant: "",
  Sellable: false,
  ProductSearchCriteria: "",
  Name: " EGSRTULUFXDiversify ",
  ShortDescription:
    "Action is to increase Term deposit product with bank, for customer with currency other than HKD",
  GroupID: "Deposits",
  PaidAudienceName: "",
  Identifier: "/AcquisitionSales/Deposits/ EGSRTULUFXDiversify",
  BundleType: "",
  Placement: "diversify_page",
  SellableStartDate: "19700101T000000.000 GMT",
  JourneyStep: "",
  Propensity: 0.0,
  AgentCompensation: 0,
  BannerLabel: "",
  ClassIdentifier: "Offer",
  Priority: 4.99999999e8,
  Channel: "Mobile",
  BundleName: "",
  ImageURL: "",
  Title2: "",
  Variant: "",
  Fields: [
    {
      Value: "N",
      Name: "FirstTrade",
    },
  ],
  InternalCost: 0,
  ProductCategory: "",
  Journey: "",
  Group: "Deposits",
  Category: "",
  Message: "立即爲您的3個月USD定存續期，獲享3.89％年利率！",
  SubjectName: "3440000001689575",
  ButtonName2: "",
  Direction: "Inbound",
  ExpectedRevenue: 0.0,
  ButtonName: "解鎖尊屬續期優惠",
  Pricing: "",
  BannerLabel2: "",
  JourneyStage: "",
  EligibilityDescription: "",
  Message2: "",
  Title: "按此解鎖尊屬優惠!",
  Rank: 2,
  ProductID: "",
  BundleParent: "false",
  Treatment: "NewTimeDepositForeignCurrency_TC",
  ProductsCompatible: "",
  AssociatedProductIDs: "",
  CampaignID: "NBA",
  OfferValue: 0,
  SubCategory: "",
  ClickThroughURL: "scmobile://web/htd-webview?specialPricing=Y",
  ProductDescription: "",
  ClickThroughURL2: "",
  SubjectID: "3440000001689575",
  ProductsIncompatible: "",
  DecisionTime: "20250130T040900.486 GMT",
  ContextName: "Customer",
};

// 8. EGSRTULUUTDiversify: diversify_page
const EGSRTULUUTDiversifyRes = {
  Issue: "AcquisitionSales",
  InteractionID: "-3569455782704439973",
  ProductName: "",
  CustomerCost: 0.0,
  ContentFormat: "Image",
  SellableEndDate: "19700101T000000.000 GMT",
  Label: " EGSRTULUUTDiversify ",
  PaidLookalikeValue: "",
  Benefits:
    "Action is to increase Term deposit product with bank, for customer with currency other than HKD",
  WhyRelevant: "",
  Sellable: false,
  ProductSearchCriteria: "",
  Name: " EGSRTULUUTDiversify ",
  ShortDescription:
    "Action is to increase Term deposit product with bank, for customer with currency other than HKD",
  GroupID: "Deposits",
  PaidAudienceName: "",
  Identifier: "/AcquisitionSales/Deposits/ EGSRTULUUTDiversify",
  BundleType: "",
  Placement: "diversify_page",
  SellableStartDate: "19700101T000000.000 GMT",
  JourneyStep: "",
  Propensity: 0.0,
  AgentCompensation: 0,
  BannerLabel: "",
  ClassIdentifier: "Offer",
  Priority: 4.99999999e8,
  Channel: "Mobile",
  BundleName: "",
  ImageURL: "",
  Title2: "",
  Variant: "",
  Fields: [
    {
      Value: "Y",
      Name: "OpenAccount",
    },
    {
      Value: "N",
      Name: "FirstTrade",
    },
    {
      Value: "N",
      Name: "CompletionBonus",
    },
  ],
  InternalCost: 0,
  ProductCategory: "",
  Journey: "",
  Group: "Deposits",
  Category: "",
  Message: "立即爲您的3個月USD定存續期，獲享3.89％年利率！",
  SubjectName: "3440000001689575",
  ButtonName2: "",
  Direction: "Inbound",
  ExpectedRevenue: 0.0,
  ButtonName: "解鎖尊屬續期優惠",
  Pricing: "",
  BannerLabel2: "",
  JourneyStage: "",
  EligibilityDescription: "",
  Message2: "",
  Title: "按此解鎖尊屬優惠!",
  Rank: 2,
  ProductID: "",
  BundleParent: "false",
  Treatment: "NewTimeDepositForeignCurrency_TC",
  ProductsCompatible: "",
  AssociatedProductIDs: "",
  CampaignID: "NBA",
  OfferValue: 0,
  SubCategory: "",
  ClickThroughURL: "scmobile://web/htd-webview?specialPricing=Y",
  ProductDescription: "",
  ClickThroughURL2: "",
  SubjectID: "3440000001689575",
  ProductsIncompatible: "",
  DecisionTime: "20250130T040900.486 GMT",
  ContextName: "Customer",
};

// 9. EGSRTULUTradeupTracker: TrackerPage
const EGSRTULUTradeupTrackerRes = {
  Issue: "AcquisitionSales",
  InteractionID: "-3569455782704439973",
  ProductName: "",
  CustomerCost: 0.0,
  ContentFormat: "Image",
  SellableEndDate: "19700101T000000.000 GMT",
  Label: " EGSRTULUTradeupTracker ",
  PaidLookalikeValue: "",
  Benefits:
    "Action is to increase Term deposit product with bank, for customer with currency other than HKD",
  WhyRelevant: "",
  Sellable: false,
  ProductSearchCriteria: "",
  Name: " EGSRTULUTradeupTracker ",
  ShortDescription:
    "Action is to increase Term deposit product with bank, for customer with currency other than HKD",
  GroupID: "Deposits",
  PaidAudienceName: "",
  Identifier: "/AcquisitionSales/Deposits/ EGSRTULUTradeupTracker ",
  BundleType: "",
  Placement: "diversify_page",
  SellableStartDate: "19700101T000000.000 GMT",
  JourneyStep: "",
  Propensity: 0.0,
  AgentCompensation: 0,
  BannerLabel: "",
  ClassIdentifier: "Offer",
  Priority: 4.99999999e8,
  Channel: "Mobile",
  BundleName: "",
  ImageURL: "",
  Title2: "",
  Variant: "",
  Fields: [
    {
      Value: "100",
      Name: "RewardValue",
    },
    {
      Value: "2",
      Name: "RewardCount",
    },
    {
      Value: "300",
      Name: "ConsolidatedAmount",
    },
  ],

  InternalCost: 0,
  ProductCategory: "",
  Journey: "",
  Group: "Deposits",
  Category: "",
  Message: "立即爲您的3個月USD定存續期，獲享3.89％年利率！",
  SubjectName: "3440000001689575",
  ButtonName2: "",
  Direction: "Inbound",
  ExpectedRevenue: 0.0,
  ButtonName: "解鎖尊屬續期優惠",
  Pricing: "",
  BannerLabel2: "",
  JourneyStage: "",
  EligibilityDescription: "",
  Message2: "",
  Title: "按此解鎖尊屬優惠!",
  Rank: 2,
  ProductID: "",
  BundleParent: "false",
  Treatment: "NewTimeDepositForeignCurrency_TC",
  ProductsCompatible: "",
  AssociatedProductIDs: "",
  CampaignID: "NBA",
  OfferValue: 0,
  SubCategory: "",
  ClickThroughURL: "scmobile://web/htd-webview?specialPricing=Y",
  ProductDescription: "",
  ClickThroughURL2: "",
  SubjectID: "3440000001689575",
  ProductsIncompatible: "",
  DecisionTime: "20250130T040900.486 GMT",
  ContextName: "Customer",
};

// 10. EGSRTULULevelupArticlenQuiz: LevelUpPage
const EGSRTULULevelupArticlenQuizRes = {
  Issue: "AcquisitionSales",
  InteractionID: "-3569455782704439973",
  ProductName: "",
  CustomerCost: 0.0,
  ContentFormat: "Image",
  SellableEndDate: "19700101T000000.000 GMT",
  Label: "EGSRTULULevelupArticlenQuizRes",
  PaidLookalikeValue: "",
  Benefits:
    "Action is to increase Term deposit product with bank, for customer with currency other than HKD",
  WhyRelevant: "",
  Sellable: false,
  ProductSearchCriteria: "",
  Name: "EGSRTULULevelupArticlenQuizRes",
  ShortDescription:
    "Action is to increase Term deposit product with bank, for customer with currency other than HKD",
  GroupID: "Deposits",
  PaidAudienceName: "",
  Identifier: "/AcquisitionSales/Deposits/ EGSRTULULevelupArticlenQuizRes",
  BundleType: "",
  Placement: "levelup_page",
  SellableStartDate: "19700101T000000.000 GMT",
  JourneyStep: "",
  Propensity: 0.0,
  AgentCompensation: 0,
  BannerLabel: "",
  ClassIdentifier: "Offer",
  Priority: 4.99999999e8,
  Channel: "Mobile",
  BundleName: "",
  ImageURL: "",
  Title2: "",
  Variant: "",
  Fields: [
    {
      Value: "N",
      Name: "ArticleReadFlag",
    },
    {
      Value: "100",
      Name: "ArticleConsolidatedAmount",
    },
    {
      Value: "Y",
      Name: "QuizFlag",
    },
    {
      Value: "200",
      Name: "QuizConsolidatedAmount",
    },
  ],

  InternalCost: 0,
  ProductCategory: "",
  Journey: "",
  Group: "Deposits",
  Category: "",
  Message: "立即爲您的3個月USD定存續期，獲享3.89％年利率！",
  SubjectName: "3440000001689575",
  ButtonName2: "",
  Direction: "Inbound",
  ExpectedRevenue: 0.0,
  ButtonName: "解鎖尊屬續期優惠",
  Pricing: "",
  BannerLabel2: "",
  JourneyStage: "",
  EligibilityDescription: "",
  Message2: "",
  Title: "按此解鎖尊屬優惠!",
  Rank: 2,
  ProductID: "",
  BundleParent: "false",
  Treatment: "NewTimeDepositForeignCurrency_TC",
  ProductsCompatible: "",
  AssociatedProductIDs: "",
  CampaignID: "NBA",
  OfferValue: 0,
  SubCategory: "",
  ClickThroughURL: "scmobile://web/htd-webview?specialPricing=Y",
  ProductDescription: "",
  ClickThroughURL2: "",
  SubjectID: "3440000001689575",
  ProductsIncompatible: "",
  DecisionTime: "20250130T040900.486 GMT",
  ContextName: "Customer",
};

// Export as an object
export const responseData = {
  EGSRTULUEntryRes,
  EGSRTULURegistrationRes,
  EGSRTULUDiversifyRes,
  EGSRTULUTradeUpRes,
  EGSRTULULevelUpRes,
  EGSRTULUOEDiversifyRes,
  EGSRTULUFXDiversifyRes,
  EGSRTULUUTDiversifyRes,
  EGSRTULUTradeupTrackerRes,
  EGSRTULULevelupArticlenQuizRes,
};
